apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: guestbook
      valueFiles:
        - values.yaml
        - ./../custom-values.yaml
    path: chart
    repoURL: https://github.com/jguilhermeam/argocd-tests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
