apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    name: meu-cluster
    namespace: my-nginx
  project: default
  source:
    path: nginx
    repoURL: https://github.com/jguilhermeam/argocd-tests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
