apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
  project: default
  source:
    helm:
      releaseName: guestbook
    path: chart
    repoURL: https://github.com/jguilhermeam/argocd-tests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
